### ISSUE TITLE
Entre ID SCIM Validator says attribute name for User is not supported

### ISSUE THREAD

**Issue by caspariel** [limosa-io/laravel-scim-server#103]
First, thanks for this package. Apologies in advance for probably a noob question.
I'm trying to set up an app for use with MS Entre ID and checking it with the [Entra ID SCIM Validator](https://scimvalidator.microsoft.com/).
Using the playground at https://api.scim.dev, the validator detects the schema using the discover schema option.
But when I then test the schema, the validator errors with:
`SCIM Validation failed. The attribute name for User is not supported by the SCIM protocol. Please refer to the SCIM RFC`
As nearly as I can tell, Entre's validator wants the schema json for the name attribute to look like:
```
"name":{
       "familyName":"Jensen",
       "givenName":"Barbara"
     },
```
Whereas the playground schema has:
```
{
          "name": "name",
          "type": "string",
          "mutability": "readWrite",
          "returned": "default",
          "uniqueness": "server",
          "required": false,
          "multiValued": false,
          "caseExact": false,
          "subAttributes": [
            {
              "name": "formatted",
              "type": "string",
              "mutability": "readWrite",
              "returned": "default",
              "uniqueness": "server",
              "required": false,
              "multiValued": false,
              "caseExact": false
            },
            {
              "name": "familyName",
              "type": "string",
              "mutability": "readWrite",
              "returned": "default",
              "uniqueness": "server",
              "required": false,
              "multiValued": false,
              "caseExact": false
            },
            {
              "name": "givenName",
              "type": "string",
              "mutability": "readWrite",
              "returned": "default",
              "uniqueness": "server",
              "required": false,
              "multiValued": false,
              "caseExact": false
            }
          ]
        },
```
Is this a known difference with Entre ID's SCIM implementation?

**Comment by arietimmerman** [comment]
Turned out the package contained a bug.
I have not tested the Entra ID SCIM validator again, but this particular issue should be fixed now. The problem was  that field `name` had type `string` while it should have been `complex`.

**Comment by caspariel** [comment]
Thank you!

**Comment by arietimmerman** [comment]
Now fixed on scim.dev as well: https://api.scim.dev/scim/v2/Schemas

I case you haven't done already, don't forget to :star: this repo
