### ISSUE TITLE
for requests with multiple schemas, the first is taken and used for validation

### ISSUE THREAD

**Issue by pieterdt** [limosa-io/laravel-scim-server#46]
In the postman test collection I found in the SCIM pages from Microsoft (https://www.postman.com/collections/3b5c4b838ec66cacd53b) There is a test for en 'Enterprise User' which carries 2 schemas. The regular User schema and an additional EnterpriseUser schema.

If the body lists the Enterprise user first, validation fails, if it is listed after the normal user schema it works.  I would expect that this order should not matter. I could work around it by doing multiple validations (one per schema) in stead of only the first, but I'm not very confident if that is the right approach?

**Comment by arietimmerman** [comment]
The order should not matter.
@pieterdt, can you specify the exact example you are testing with? And also include your SCIMConfig mapping (adjustments).
