### ISSUE TITLE
Add the body's to remove a member from a group

### ISSUE THREAD

**Issue by tuk90** [limosa-io/laravel-scim-server#59]
Under the groups endpoint you now have an example to add a user to a group, could you also add the remove user from a group? Both the offical documented way as documented in: https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2.2

```
   {
     "schemas":
      ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations":[{
       "op":"remove",
       "path":"members[value eq \"32368858-e1e5-4f05-9306-682625714ec0\"]"
     }]
   }
```

And the, as far as I know, not documented variant by the RFC but the used option by many providers:

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "add",
      "path": "members",
      "value": [
        {
          "value": "32368858-e1e5-4f05-9306-682625714ec0"
        }
      ]
    }
  ]
}
```

There are more options to do it, but from my experience these two are the most used.

**Comment by arietimmerman** [comment]
Thanks for the suggestion. Here you have it => https://scim.dev/playground/groups.html#remove-user-from-group
