### ISSUE TITLE
Any chance to release the server component as separated package without requiring laravel?

### ISSUE THREAD

**Issue by ulfw** [limosa-io/laravel-scim-server#61]
I was searching for a library that provides the server capabilities for scim provisioning and found this one.
But we are not using laravel, sois there any change to decouple the server component from laravel?

best regards
Ulf

**Comment by arietimmerman** [comment]
This is not planned.
It should be possible to rewrite it without using Laravel libraries. Primarily Laravel Eloquent is used for transforming SCIM requests into database queries. However, this could be replaced for something more generic.
