### ISSUE TITLE
versioning strategy

### ISSUE THREAD

**Issue by flaviu-chelaru** [limosa-io/laravel-scim-server#66]
From: https://semver.org/

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backward compatible manner
PATCH version when you make backward compatible bug fixes

1. https://github.com/limosa-io/laravel-scim-server/compare/v0.6.8...v0.6.9
This version has not fixed any bug
Expected: minor version
Actual: fix version

2. https://github.com/limosa-io/laravel-scim-server/compare/v0.6.4...v0.6.5
This version has introduced a new feature.
The feature uses PHP8 specific syntax

Expected - composer json updates the minimum php required version
Expected - minor version bump
Expected - phpunit tests catch this kind of backwards incompatible changes.

Actual: patch bump
Actual: tests pass
Actual: composer json mentions support for php7 (which is false)

Based on these notes, I would conclude that this library might be unreliable to use in projects where SEMVER versioning is used as a best practice.

**Comment by arietimmerman** [comment]
Probably you are right. I could consider following are more structured versioning approach.

**Comment by arietimmerman** [comment]
Now, I have introduced a breaking change and decided to follow semantic versioning.
