### ISSUE TITLE
Bug : sending invalid input should not returun 500 but a 400

### ISSUE THREAD

**Issue by LasneF** [limosa-io/laravel-scim-server#74]
**Description **

given an invalid input server rertuns 500 , where it should return 400 error code ( payload is ok) 

**How to Reproduce**
given the request 

POST : https://api.scim.dev/scim/v2/Groups 

with **no payload** 

the server return 

```
status code 500 + this payload 
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Missing a valid schemas-attribute.",
    "status": 500
}
````

**Comment by arietimmerman** [comment]
It took a while, but I've just fixed this. Thanks for reporting.
