### ISSUE TITLE
SCIM : group implementation; , name should not be mandatory as per RFC

### ISSUE THREAD

**Issue by LasneF** [limosa-io/laravel-scim-server#75]
Even if SCIM is a flexible specification , your sample should stick to the standard in term of mandatory fields to not break the contract (even if scim allows discovery of the contract ) 

the issue i got is about Group , Group defined data model is  composed of 

[Common Section ](https://www.rfc-editor.org/rfc/rfc7643#section-3.1)  around id , externalId and meta 

and a 

[Group Specific](https://www.rfc-editor.org/rfc/rfc7643#section-4.2) around displayName ( Mandatory ) and members that can be mandatory or not based on the implementation , and the return of /Schemas/urn:ietf:params:scim:schemas:core:2.0:Group 

but name is not mentionned , making it mandatory breaks the "Default" implementation of the RFC and imply to do specific mapping 

otherwise got this error 

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "detail": "Invalid data!",
  "status": 400,
  "scimType": "invalidSyntax",
  "errors": {
    "urn:ietf:params:scim:schemas:core:2.0:Group:name": [
      "The urn:ietf:params:scim:schemas:core:2.0: group:name field is required."
    ]
  }
}

``` 
the GET https://api.scim.dev/scim/v2/Schemas/urn:ietf:params:scim:schemas:core:2.0:Group

should not have as well 

  "attributes": [
    {
      "name": "name",
      "type": "string",
      "mutability": "readWrite",
      "returned": "default",
      "uniqueness": "server",
      **"required": true,**
      "multiValued": false,
      "caseExact": false
    },

**Comment by arietimmerman** [comment]
Thanks for pointing out. Now it's fixed : https://scim.dev/playground/groups.html#create-group
