### ISSUE TITLE
Ignore fields

### ISSUE THREAD

**Issue by struyfv** [limosa-io/laravel-scim-server#92]
Hi,

In the previous version (version ^0.6.2), when I wanted to ignore an incoming field I did it like this:

`(new AttributeMapping())->ignoreWrite()->ignoreRead(),`

But how can I ignore a field now? I don't want to map it in my database.

**Comment by arietimmerman** [comment]
Currently, I guess the best way i to use something like below in your configuration.
That is, use an anonymous class and extend a class like `Eloquent`. Next, override the patch/replace/add methods.

If you need more help, let me know.

~~~.php
(new class ('id') extends Eloquent {
    public function patch($operation, $value, Model &$object, ?Path $path = null)
    {
        // do nothing
    }
    public function replace($value, &$object, $path = null)
    {
        // do nothing
    }
    public function add($value, &$object)
    {
        // do nothing
    }
}  
~~~
